name: citric
description: Adicionar biblioteca Citric para React Stack

types:
  - app

tags:
  - "orange-stackfront-web-scaffold"
  - "orange-stackfront-web-shell-scaffold"
  - "orange-stackfront-web-citric-plugin"

# Nome com formatação livre que será exibido no portal.
displayName: Citric

# caso a picture esteja fora do repo colocar uma url externa
# Categorias disponíveis:
# [sre, frontend, backend, fullStack, analytics]
picture: "logo.png"

# Especificar a categoria da stack.
# Plugin podem perceber a qualquer category
category: frontend, design-system

## Lista de tecnologias que você gostaria de enfatizar que é compativel
compatibility:
  - reactjs

# Especificar um arquivo .md que explique o about do template
# por padrão o valor é about.md
about: about.md
# Especificar um arquivo .md que explique o usage do template
# por padrão o valor é usage.md
usage: usage.md
# Especificar um arquivo .md que explique useCase do template
# por padrão o valor é usage.md
useCase: useCase.md
# Especificar um arquivo .md que explique a implementation do template
# por padrão o valor é implementation.md
implementation: implementation.md

# tecnologies que o plugin utiliza
# A lista completa das tecnologias que podem ser cadastradas estão disponiveis na Documentação
technologies: [ "ReactJS", "NextJS" ]
